MOSIP-25809 Compared sub of id-token and auth token for resident API.
mosip/mosip-openid-bridge pull request #170
Opened 2023-01-30 06:09 UTC by kameshsr

2023-01-30 06:24 UTC, LoganathanSekar7627 requested changes

2023-01-30 06:24 UTC, LoganathanSekar7627 commented on kernel/kernel-auth-adapter/src/main/java/io/mosip/kernel/auth/defaultadapter/filter/AuthFilter.java
> +										throw new ClientException(Errors.TOKEN_NOTPRESENT_ERROR.getErrorCode(),
check for empty also

2023-01-30 06:24 UTC, LoganathanSekar7627 commented on kernel/kernel-auth-adapter/src/main/java/io/mosip/kernel/auth/defaultadapter/filter/AuthFilter.java
> +								idTokenSub = getSubClaimValueFromToken(token);
This should be from idToken instead of token

2023-01-30 06:24 UTC, LoganathanSekar7627 commented on kernel/kernel-auth-adapter/src/main/java/io/mosip/kernel/auth/defaultadapter/filter/AuthFilter.java
> +		return JWT.decode(token).getClaim((String) Constants.SUB).asString();
Make use of the property for the sub claim name.

2023-01-30 06:24 UTC, LoganathanSekar7627 commented on kernel/kernel-authcodeflowproxy-api/src/main/java/io/mosip/kernel/authcodeflowproxy/api/controller/LoginController.java
> +		return JWT.decode(token).getClaim((String) Constants.SUB).asString();
User claim name property

2023-01-30 06:26 UTC, kameshsr commented on kernel/kernel-auth-adapter/src/main/java/io/mosip/kernel/auth/defaultadapter/filter/AuthFilter.java
> +										throw new ClientException(Errors.TOKEN_NOTPRESENT_ERROR.getErrorCode(),
Done.

2023-01-30 06:28 UTC, kameshsr commented on kernel/kernel-auth-adapter/src/main/java/io/mosip/kernel/auth/defaultadapter/filter/AuthFilter.java
> +								idTokenSub = getSubClaimValueFromToken(token);
corrected

2023-01-30 09:55 UTC, kameshsr commented on kernel/kernel-auth-adapter/src/main/java/io/mosip/kernel/auth/defaultadapter/filter/AuthFilter.java
> +		return JWT.decode(token).getClaim((String) Constants.SUB).asString();
done.

2023-01-30 09:55 UTC, kameshsr commented on kernel/kernel-authcodeflowproxy-api/src/main/java/io/mosip/kernel/authcodeflowproxy/api/controller/LoginController.java
> +		return JWT.decode(token).getClaim((String) Constants.SUB).asString();
done.

2023-02-08 07:41 UTC, LoganathanSekar7627 reviewed
`private String getSubClaimValueFromToken(String token) {
		return JWT.decode(token).getClaim(this.environment.getProperty(Constants.TOKEN_SUBJECT_CLAIM_NAME)).asString();
	}`

2023-02-08 07:41 UTC, LoganathanSekar7627 commented on kernel/kernel-auth-adapter/src/main/java/io/mosip/kernel/auth/defaultadapter/filter/AuthFilter.java
> +						authTokenSub = getSubClaimValueFromToken(token);
Please add the condition around this statement to avoid unnecessary computation if the flag is disabled: 	if(validateIdToken){

2023-02-08 08:29 UTC, kameshsr commented on kernel/kernel-auth-adapter/src/main/java/io/mosip/kernel/auth/defaultadapter/filter/AuthFilter.java
> +						authTokenSub = getSubClaimValueFromToken(token);
done.

2023-02-08 09:51 UTC, LoganathanSekar7627 requested changes

2023-02-08 09:51 UTC, LoganathanSekar7627 commented on kernel/kernel-authcodeflowproxy-api/src/main/java/io/mosip/kernel/authcodeflowproxy/api/controller/LoginController.java
> +		String authTokenSub =  AuthCodeProxyFlowUtils.getSubClaimValueFromToken
Here also check for the flag and then get the sub claim

2023-02-08 10:15 UTC, kameshsr commented on kernel/kernel-authcodeflowproxy-api/src/main/java/io/mosip/kernel/authcodeflowproxy/api/controller/LoginController.java
> +		String authTokenSub =  AuthCodeProxyFlowUtils.getSubClaimValueFromToken
done

2023-02-08 10:19 UTC, LoganathanSekar7627 approved these changes

2023-02-08 15:30 UTC, mahammedtaheer approved these changes

2023-02-08 15:30 UTC, merged