MOSIP-28139 added handleCtkTokenFlow method
mosip/mosip-openid-bridge pull request #185
Opened 2023-07-04 11:03 UTC by mayuradesh

2023-08-01 07:14 UTC, mahammedtaheer requested changes

2023-08-03 06:26 UTC, mayuradesh commented on kernel/kernel-auth-adapter/src/main/java/io/mosip/kernel/auth/defaultadapter/filter/AuthFilter.java
> +		for (Map.Entry<String, String[]> entry : requestParams.entrySet()) {
Updated code

2023-08-03 06:26 UTC, mayuradesh commented on kernel/kernel-auth-adapter/src/main/java/io/mosip/kernel/auth/defaultadapter/filter/AuthFilter.java
> +			String ctkSaveUrl = environment.getProperty("mosip.compliance.toolkit.saveDataShareToken.url");
done

2023-08-03 06:26 UTC, mayuradesh commented on kernel/kernel-auth-adapter/src/main/java/io/mosip/kernel/auth/defaultadapter/filter/AuthFilter.java
> +			valueMap.put(AuthAdapterConstant.TOKEN, token);
Updated code

2023-08-03 06:26 UTC, mayuradesh commented on kernel/kernel-auth-adapter/src/main/java/io/mosip/kernel/auth/defaultadapter/filter/AuthFilter.java
> +			LOGGER.debug("Calling Compliance Toolkit requestWrapper: " + requestWrapper);
updated code

2023-08-03 06:28 UTC, mayuradesh commented on kernel/kernel-auth-adapter/src/main/java/io/mosip/kernel/auth/defaultadapter/filter/AuthFilter.java
> +					tokenUrl = new StringBuilder(ctkInvalidateUrl).toString();
added @value annotation
Two separate urls perform two separate logic
in one , token is expired before saving to db and in one token is directly save in db

2023-08-03 06:28 UTC, mayuradesh commented on kernel/kernel-auth-adapter/src/main/java/io/mosip/kernel/auth/defaultadapter/filter/AuthFilter.java
> +				LOGGER.error("error connecting to compliance toolkit {}", e.getLocalizedMessage());
done

2023-08-07 10:00 UTC, mahammedtaheer commented on kernel/kernel-auth-adapter/src/main/java/io/mosip/kernel/auth/defaultadapter/filter/AuthFilter.java
> +				LOGGER.error("error connecting to compliance toolkit {}", e.getLocalizedMessage());
getStackTrace() method returns StackTraceElement object array, the log statement convert it to string which will not give stacktrack. Please use "error(String message, Throwable throwable)" method to print stacktrack in logs.

2023-08-07 10:49 UTC, mahammedtaheer approved these changes

2023-08-07 10:49 UTC, merged