[MOSIP-29250] Updated workflows as per reusable workflows templates (…
mosip/mosip-openid-bridge pull request #203
Opened 2023-09-25 10:39 UTC by Rakshithb1

…#202)

2023-09-25 11:05 UTC, syedsalman3753 requested changes
please update clear-artifacts.yml

2023-09-25 12:19 UTC, Rakshithb1 commented
updated clear-artifacts.yml

2023-09-25 13:19 UTC, syedsalman3753 approved these changes

2023-09-26 05:33 UTC, ckm007 approved these changes

2023-09-26 05:33 UTC, merged