MOSIP-15286 Generating openapi.json for Auth-Service
mosip/mosip-openid-bridge pull request #24
Opened 2021-11-19 06:27 UTC by kameshsr

Resolved Merge conflict

2021-11-19 12:47 UTC, vishwa-vyom requested changes

2021-11-19 12:47 UTC, vishwa-vyom commented on kernel/kernel-auth-service/pom.xml
> +			<id>local</id>
This profile is not correct

2021-11-19 12:55 UTC, kameshsr commented on kernel/kernel-auth-service/pom.xml
> +			<id>local</id>
yes sir i have fixed.

2021-11-22 05:30 UTC, vishwa-vyom approved these changes

2021-12-14 05:48 UTC, m1054352 approved these changes

2021-12-16 11:05 UTC, mandeepdhiman123 approved these changes

2021-12-16 11:05 UTC, merged