Added test case to improve coverage
mosip/mosip-openid-bridge pull request #246
Opened 2024-03-14 05:21 UTC by kaifk468

2024-03-24 18:28 UTC, ase-101 commented on kernel/kernel-auth-service/src/test/java/io/mosip/kernel/auth/service/test/AuthServiceTest.java
> +	public void authenticateUserWithValidUsernameTest() throws Exception {
This test case is about the success response from keycloak, in this case test case should also be named based on what we are testing @kaifk468. Can you rename the test case. Please follow the test case naming convention.
convention -> methodNameToTest_testCaseName_testCaseResult

2024-03-24 18:29 UTC, ase-101 commented on kernel/kernel-auth-service/src/test/java/io/mosip/kernel/auth/service/test/AuthServiceTest.java
> +	public void authenticateUserWithInValidUsername_thenFail() throws Exception {
This test case is about the 401 response from the keycloak server, in this case test case should be named based on what we are testing @kaifk468. Can you rename the test case. Please follow the test case naming convention -> methodNameToTest_testCaseName_testCaseResult

2024-03-24 18:29 UTC, ase-101 commented on kernel/kernel-auth-service/src/test/java/io/mosip/kernel/auth/service/test/AuthServiceTest.java
> +	public void authenticateUserWithBadRequest_thenFail() throws Exception {
This test case is about the 400 response from the keycloak server, in this case test case should be named based on what we are testing @kaifk468. Can you rename the test case. Please follow the test case naming convention -> methodNameToTest_testCaseName_testCaseResult

2024-03-24 18:31 UTC, ase-101 commented on kernel/kernel-auth-service/src/test/java/io/mosip/kernel/auth/service/test/AuthServiceTest.java
> +	public void authenticateUserWithInvalidResponse_thenFail() throws Exception {
Here also, the above comment is applicable.

2024-03-24 18:34 UTC, ase-101 commented on kernel/kernel-auth-service/src/test/java/io/mosip/kernel/auth/service/test/AuthServiceTest.java
> +			assertThat(e.getMessage(),is("Invalid User Id type"));
Instead of an error message can we assert on the error code? It is always better to assert based on the error code as it's less likely to change. one more advice is to reuse the error code constant instead of hard-coding the error code.

2024-03-24 18:43 UTC, ase-101 commented on kernel/kernel-auth-service/src/test/java/io/mosip/kernel/auth/service/test/AuthServiceTest.java
> +			authService.authenticateUser(loginUser);
There are still 2 more test cases that can be added, one for server_error and the other realm_not_found please check.

2024-03-24 18:48 UTC, ase-101 commented on kernel/kernel-auth-service/src/test/java/io/mosip/kernel/auth/service/test/AuthServiceTest.java
> +			assertThat(e.getMessage(),is("Invalid User Id type"));
Also, can we verify if the respective methods are invoked based on the userIdType?

2024-03-24 18:54 UTC, ase-101 commented on kernel/kernel-auth-service/src/test/java/io/mosip/kernel/auth/service/test/AuthServiceTest.java
> +	public void authenticateWithSecretKeyWithInValidDetatils_thenPass() throws Exception {
The test case name does not reflect the written test case. This is a negative test case, right?

2024-03-24 19:01 UTC, ase-101 commented on kernel/kernel-auth-service/src/test/java/io/mosip/kernel/auth/service/test/AuthServiceTest.java
> +	public void logoutUser_ValidDetails_thenPass(){
Here are also we are missing logout with "invalid_token" and the keycloak server returning 5xx errors

2024-03-24 19:03 UTC, ase-101 commented on kernel/kernel-auth-service/src/test/java/io/mosip/kernel/auth/service/test/AuthServiceTest.java
> +	public void loginRedirect_ValidDetails_thenPass() throws Exception {
why is there no negative test case on the loginRedirect method? @kaifk468

2024-03-24 19:05 UTC, ase-101 commented on kernel/kernel-auth-service/src/test/java/io/mosip/kernel/auth/service/test/AuthServiceTest.java
> +		authService.refreshToken("app-id","refresh-token",refreshTokenRequest);
Why is the test result not asserted?

2024-03-24 19:07 UTC, ase-101 commented on kernel/kernel-auth-service/src/test/java/io/mosip/kernel/auth/service/test/AuthServiceTest.java
> +	public void valdiateToken_ValidInDetails_thenPass() throws Exception {
This is a negative test case but why is the test case named as _thenPass?

2024-03-24 19:08 UTC, ase-101 requested changes
Please check the comment in authServiceImplTest and try to fix the similar kind of issues in the remaining 3 test files @kaifk468

2024-03-25 16:26 UTC, kaifk468 commented on kernel/kernel-auth-service/src/test/java/io/mosip/kernel/auth/service/test/AuthServiceTest.java
> +	public void authenticateUserWithValidUsernameTest() throws Exception {
changed the name

2024-03-25 16:26 UTC, kaifk468 commented on kernel/kernel-auth-service/src/test/java/io/mosip/kernel/auth/service/test/AuthServiceTest.java
> +	public void authenticateUserWithInValidUsername_thenFail() throws Exception {
changed the name

2024-03-25 16:26 UTC, kaifk468 commented on kernel/kernel-auth-service/src/test/java/io/mosip/kernel/auth/service/test/AuthServiceTest.java
> +	public void authenticateUserWithBadRequest_thenFail() throws Exception {
changed the name

2024-03-25 16:27 UTC, kaifk468 commented on kernel/kernel-auth-service/src/test/java/io/mosip/kernel/auth/service/test/AuthServiceTest.java
> +	public void authenticateUserWithInvalidResponse_thenFail() throws Exception {
changed the name

2024-03-25 16:28 UTC, kaifk468 commented on kernel/kernel-auth-service/src/test/java/io/mosip/kernel/auth/service/test/AuthServiceTest.java
> +	public void authenticateWithSecretKeyWithInValidDetatils_thenPass() throws Exception {
changed

2024-03-25 20:09 UTC, kaifk468 commented on kernel/kernel-auth-service/src/test/java/io/mosip/kernel/auth/service/test/AuthServiceTest.java
> +	public void loginRedirect_ValidDetails_thenPass() throws Exception {
added a negative testcase

2024-03-25 20:13 UTC, kaifk468 commented on kernel/kernel-auth-service/src/test/java/io/mosip/kernel/auth/service/test/AuthServiceTest.java
> +		authService.refreshToken("app-id","refresh-token",refreshTokenRequest);
added assertion

2024-03-25 20:14 UTC, kaifk468 commented on kernel/kernel-auth-service/src/test/java/io/mosip/kernel/auth/service/test/AuthServiceTest.java
> +	public void valdiateToken_ValidInDetails_thenPass() throws Exception {
changed

2024-03-25 20:40 UTC, kaifk468 commented on kernel/kernel-auth-service/src/test/java/io/mosip/kernel/auth/service/test/AuthServiceTest.java
> +			authService.authenticateUser(loginUser);
added test case for server_error but not able to locate realm not found code

2024-04-29 07:26 UTC, mahammedtaheer approved these changes

2024-04-30 07:29 UTC, ckm007 approved these changes

2024-05-01 17:19 UTC, merged